declare const RACES: {
    1: "human";
    2: "orc";
    3: "dwarf";
    4: "nightelf";
    5: "scourge";
    6: "tauren";
    7: "gnome";
    8: "troll";
    10: "bloodelf";
    11: "draenei";
};

declare const modelingType: {
    ARMOR: 128;
    CHARACTER: 16;
    COLLECTION: 1024;
    HELM: 2;
    HUMANOIDNPC: 32;
    ITEM: 1;
    ITEMVISUAL: 512;
    NPC: 8;
    OBJECT: 64;
    PATH: 256;
    SHOULDER: 4;
};
declare const characterPart: {
    Face: string;
    "Skin Color": string;
    "Hair Style": string;
    "Hair Color": string;
    "Facial Hair": string;
    Mustache: string;
    Beard: string;
    Sideburns: string;
    "Face Shape": string;
    Eyebrow: string;
    "Jaw Features": undefined;
    "Face Features": undefined;
    "Skin Type": undefined;
    Ears: string | undefined;
    "Fur Color": string | undefined;
    Snout: string;
    Blindfold: undefined;
    Tattoo: undefined;
    "Eye Color": undefined;
    "Tattoo Color": undefined;
    Armbands: undefined;
    "Jewelry Color": undefined;
    Bracelets: undefined;
    Necklace: undefined;
    Earring: undefined;
    "Primary Color": string | undefined;
    "Secondary Color Strength": string | undefined;
    "Secondary Color": string | undefined;
    "Horn Color": string | undefined;
    Horns: string | undefined;
    "Body Size": string | undefined;
};
declare function getCharacterOptions(character: Record<string, any>, fullOptions: { Options?: Array<Record<string, any>> }): Array<{ optionId: any; choiceId: any }>;
declare function optionsFromModel(model: Record<string, any>, fullOptions: Record<string, any>): { models: { id: string; type: number }; charCustomization?: { options: Array<{ optionId: any; choiceId: any }> }; items: any[] };
declare function getDisplaySlot(item: number, slot: number, displayId: number): Promise<{ displaySlot: number; displayId: number }>;
declare function findItemsInEquipments(equipments: any[]): Promise<Array<[number, number]>>;
declare function findRaceGenderOptions(race: number, gender: number): Promise<Record<string, any>>;
export { optionsFromModel, findRaceGenderOptions, findItemsInEquipments, getDisplaySlot, getCharacterOptions, RACES, characterPart, modelingType };
